name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

# Set the permissions for the GITHUB_TOKEN
permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  ai_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @google/generative-ai

      - name: AI Review PR Files
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Fetch the base branch to compare against
          git fetch origin ${{ github.base_ref }} --depth=1
          
          # Get changed files between base and head
          FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.sha }} --diff-filter=ACMRTUXB || true)
          
          # Create or clear the review output file
          echo "# AI Code Review\n" > review_output.md
          
          # Process each changed file
          if [ -n "$FILES" ]; then
            echo "## Changed Files" >> review_output.md
            for file in $FILES; do
              # Skip files larger than 1MB
              if [ $(wc -c <"$file") -lt 1000000 ]; then
                echo "\n### Reviewing $file" >> review_output.md
                node .ai-bot/review.js "$file" >> review_output.md 2>&1 || echo "Error processing $file" >> review_output.md
              else
                echo "\n### Skipped $file (file too large)" >> review_output.md
              fi
            done
          else
            echo "No files to review." >> review_output.md
          fi

      - name: Create Review Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const pull_number = context.issue.number;
            
            // Read the review output
            const reviewContent = fs.readFileSync('review_output.md', 'utf8');
            
            // Only post if there's content
            if (reviewContent.trim()) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pull_number,
                body: reviewContent
              });
            }

  ai_label_issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install @google/generative-ai

      - name: AI Label Issue
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          RESPONSE=$(node -e "
            import { GoogleGenerativeAI } from '@google/generative-ai';
            const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
            const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
            (async () => {
              const result = await model.generateContent(\`Suggest 3 relevant GitHub labels for this issue: ${ISSUE_BODY}\`);
              console.log(result.response.text());
            })();
          ")
          echo "Labels: $RESPONSE"
